services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    volumes:
      # Mount scripts folder
      - ./scripts:/scripts

      # Gluetun internal state directory
      - ./gluetun:/gluetun

    ports:
      - 8080:8080/tcp   # qBittorrent WebUI

    # Internal-only Gluetun API (NOT exposed to host)
    expose:
      - 8000

    environment:
      # --- Gluetun Authentication disabled as it is not exposed outside ---
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"none"}

      # --- ProtonVPN + WireGuard ---
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      
       # --- Let's give the guys a hand... (https://github.com/qdm12/gluetun) ---
      - BORINGPOLL_GLUETUNCOM=on

      # --- Port Forwarding ---
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on

      # External scripts
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md
      - VPN_PORT_FORWARDING_UP_COMMAND=/scripts/port_up.sh {{PORT}} {{VPN_INTERFACE}}
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/scripts/port_down.sh

      # Timezone
      - TZ=${TZ}

    restart: unless-stopped

  ###########################################################################
  # IMPORTANT NOTE FOR QBITTORRENT:
  #
  # To allow Gluetun to automatically update the listening port using the
  # port_up.sh and port_down.sh scripts, you MUST enable the following option
  # inside qBittorrent:
  #
  #   Tools → Options → WebUI →
  #   "Bypass authentication for clients on localhost"
  #
  # Without this option, qBittorrent will reject the API calls coming from
  # Gluetun (127.0.0.1), and port forwarding WILL NOT WORK.
  ###########################################################################

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent

    # Shares network namespace with Gluetun
    network_mode: "service:gluetun"

    depends_on:
      gluetun:
        condition: service_healthy

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080

    volumes:
      # Mount scripts folder
      - ./scripts:/scripts
      
     # qBittorrent internal state directory
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads

    # Checks port sync with Gluetun API
    healthcheck:
      test: ["CMD-SHELL", "/scripts/qbittorrent_healthcheck.sh"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 60s

    restart: unless-stopped
